//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedPlus.Data.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedCard()
        {
            this.ChangesOfPaymentTypes = new HashSet<ChangesOfPaymentType>();
            this.PatientMovements = new HashSet<PatientMovement>();
            this.Spr_Benefit = new HashSet<Spr_Benefit>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> DateTimeReceipt { get; set; }
        public Nullable<int> DepartmentID_Receipt { get; set; }
        public Nullable<int> DepartmentID_Discharge { get; set; }
        public Nullable<int> DocumentTypeID { get; set; }
        public string DocumentSeria { get; set; }
        public string DocumentNumber { get; set; }
        public string LName { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string GenderCode { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> SignOfResidenceID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string KLADR_ID { get; set; }
        public string Street { get; set; }
        public string HouseNumber { get; set; }
        public string BuildingNumber { get; set; }
        public string ApartmentNumber { get; set; }
        public string Phone { get; set; }
        public Nullable<int> SocialStatusID { get; set; }
        public string Job { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public string PolicySeria { get; set; }
        public string PolicyNumber { get; set; }
        public string SNILS { get; set; }
        public string SendingOrdanisationID { get; set; }
        public Nullable<System.DateTime> SendingDate { get; set; }
        public int HospitalizationTypeID { get; set; }
        public Nullable<int> DeliveryTypeID { get; set; }
        public string DiagnosisCode_LPU { get; set; }
        public string DiagnosisDescription_LPU { get; set; }
        public string DiagnosisCode_PO { get; set; }
        public string DiagnosisDescription_PO { get; set; }
        public Nullable<int> IsRepeated { get; set; }
        public Nullable<int> InjuryTypeID { get; set; }
        public Nullable<int> DeliveryPeriodID { get; set; }
        public Nullable<System.DateTime> DateTimeDischarge { get; set; }
        public Nullable<int> SignOfDischargeID { get; set; }
        public string DiagnosisCode_Discharge { get; set; }
        public Nullable<int> TreatmentOutcomeID { get; set; }
        public Nullable<int> DenialID { get; set; }
        public string BrigadeNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChangesOfPaymentType> ChangesOfPaymentTypes { get; set; }
        public virtual Death Death { get; set; }
        public virtual Spr_Country Spr_Country { get; set; }
        public virtual Spr_DeliveryPeriod Spr_DeliveryPeriod { get; set; }
        public virtual Spr_DeliveryType Spr_DeliveryType { get; set; }
        public virtual Spr_Denial Spr_Denial { get; set; }
        public virtual Spr_Department Spr_Department { get; set; }
        public virtual Spr_Department Spr_Department1 { get; set; }
        public virtual Spr_Diagnosis Spr_Diagnosis { get; set; }
        public virtual Spr_Diagnosis Spr_Diagnosis1 { get; set; }
        public virtual Spr_Diagnosis Spr_Diagnosis2 { get; set; }
        public virtual Spr_DocumentType Spr_DocumentType { get; set; }
        public virtual Spr_Gender Spr_Gender { get; set; }
        public virtual Spr_HospitalizationType Spr_HospitalizationType { get; set; }
        public virtual Spr_InjuryType Spr_InjuryType { get; set; }
        public virtual Spr_KLADR Spr_KLADR { get; set; }
        public virtual Spr_PaymentType Spr_PaymentType { get; set; }
        public virtual Spr_SendingOrganisation Spr_SendingOrganisation { get; set; }
        public virtual Spr_SignOfDischarge Spr_SignOfDischarge { get; set; }
        public virtual Spr_SignOfResidence Spr_SignOfResidence { get; set; }
        public virtual Spr_SocialStatus Spr_SocialStatus { get; set; }
        public virtual Spr_TreatmentOutcome Spr_TreatmentOutcome { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientMovement> PatientMovements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spr_Benefit> Spr_Benefit { get; set; }
    }
}
