//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedPlus.Data.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMovement
    {
        public int ID { get; set; }
        public int SignOfDischargeID { get; set; }
        public int DepartmentID { get; set; }
        public System.DateTime DateTimeReceipt { get; set; }
        public Nullable<System.DateTime> DateTimeDischarge { get; set; }
        public int CardID { get; set; }
    
        public virtual MedCard MedCard { get; set; }
        public virtual Spr_Department Spr_Department { get; set; }
        public virtual Spr_SignOfDischarge Spr_SignOfDischarge { get; set; }
    }
}
